name: Post-push Link Checker

on: push

jobs:
  link-check:
    name: Broken link checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/patches/github-slugger+1.3.0.patch') }}-${{ hashFiles('**/patches/vue-scrollactive+0.9.3.patch') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build and serve
        run: |
          yarn build 
          node scripts/server.js &

      - name: Wait for server 
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3000'
          responseCode: 200
          timeout: 600000
          interval: 5000

      # - name: Wait for Netlify deploy
      #   uses: probablyup/wait-for-netlify-action@3.2.0
      #   id: waitForDeployment
      #   with:
      #     site_id: ${{ secrets.NETLIFY_SITE_ID }}
      #   env:
      #     NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."

            # Find changed files in the content directory
            path_parts=(${changed_file//\// })
            CONTENT_DIR="content"

            # Skip files not in the content directory
            if [ ${changed_file%%/*} != $CONTENT_DIR ]
            then
              echo "File is not in content directory. Skipping..."
              echo "${changed_file%%/*}"
              continue
            fi

            # Skip non-markdown files
            if [ ${changed_file: -3} != ".md" ]
            then
              echo "File is not a markdown file. Skipping..."
              continue
            fi

            # Ignore changelog files (for now, because I'm a lazy developer)
            if [ path_parts[1] == "_changelogs" ]
            then
              echo "File is a changelog file. Skipping..."
              continue
            fi

            echo "Markdown file changed: $changed_file"

            # Remove "content/" from string
            file_path=${changed_file#*/}

            # Remove extension
            file_path=${file_path%.md}

            ORIGIN=http://localhost:3000
            URL_TO_CHECK=$ORIGIN/$file_path

            echo "Need to visit URL and check for broken links: $URL_TO_CHECK"

            npx broken-link-checker $URL_TO_CHECK -eo
          done
