name: Post-push Link Checker

on: push

jobs:
  link-check:
    name: Broken link checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
            # Find changed files in the content directory
            path_parts=(${changed_file//\// })
            echo ${path_parts[0]}
          done
