name: Post-push Link Checker

on: push

jobs:
  link-check:
    name: Broken link checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for Netlify deploy
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."

            # Find changed files in the content directory
            path_parts=(${changed_file//\// })
            CONTENT_DIR="content"

            # Skip files not in the content directory
            if [ ${changed_file%%/*} != $CONTENT_DIR ]
            then
              echo "File is not in content directory. Skipping..."
              echo "${changed_file%%/*}"
              continue
            fi

            # Skip non-markdown files
            if [ ${changed_file: -3} != ".md" ]
            then
              echo "File is not a markdown file. Skipping..."
              continue
            fi

            # Ignore changelog files (for now, because I'm a lazy developer)
            if [ path_parts[1] == "_changelogs" ]
            then
              echo "File is a changelog file. Skipping..."
              continue
            fi

            echo "Markdown file changed: $changed_file"

            # Remove "content/" from string
            file_path=${changed_file#*/}

            # Remove extension
            file_path=${file_path%.md}

            ORIGIN=${{ steps.waitForDeployment.outputs.url }}
            URL_TO_CHECK=$ORIGIN/$file_path

            echo "Need to visit URL and check for broken links: $URL_TO_CHECK"

            npx broken-link-checker $URL_TO_CHECK -eo
          done
